### ISSUE TITLE
when deploying a revision with a wasm module that does not exist (or bad path) the reverse-proxy shutdown

### ISSUE THREAD

**Issue by k33g** [bots-garden/capsule#107]
```
2022-08-23T04:27:10.472 app[048da343] cdg [info] 🖐[RegisterURL] {"code":"OK","function":"hey","message":"URL added to the revision","revision":"green","url":"http://localhost:10009"}

2022-08-23T04:27:10.472 app[048da343] cdg [info] 🟡[scale] Add a new wasm module to an existing revision of an existing function: green

2022-08-23T04:27:10.555 app[048da343] cdg [info] 📥 file to download https://capsule-faas.fly.dev:7043/demo/hey/0.0.0/hey.wasm

2022-08-23T04:27:10.555 app[048da343] cdg [info] 🙂 file downloaded ./tmp/07b2d625-5cdd-4e03-916c-9a3272372c1d.wasm

2022-08-23T04:27:10.556 app[048da343] cdg [info] 💊 Capsule ( v0.1.6 🦞 ) http server is listening on: 10009 🌍

2022-08-23T04:27:15.174 app[048da343] cdg [info] 2022/08/23 04:27:15 http: panic serving 176.58.95.106:33596: runtime error: index out of range [5] with length 3

2022-08-23T04:27:15.174 app[048da343] cdg [info] goroutine 2556 [running]:

2022-08-23T04:27:15.174 app[048da343] cdg [info] net/http.(*conn).serve.func1()

2022-08-23T04:27:15.174 app[048da343] cdg [info] /usr/local/go/src/net/http/server.go:1825 +0xbf

2022-08-23T04:27:15.174 app[048da343] cdg [info] panic({0x892800, 0xc000276600})

2022-08-23T04:27:15.174 app[048da343] cdg [info] /usr/local/go/src/runtime/panic.go:844 +0x258

2022-08-23T04:27:15.174 app[048da343] cdg [info] github.com/bots-garden/capsule/capsule-reverse-proxy/reverse-proxy.redirect({0xc000414c80?, 0xc00039c9c0?, 0x403f69?}, 0xc000145300)

2022-08-23T04:27:15.174 app[048da343] cdg [info] /github/workspace/capsule-reverse-proxy/reverse-proxy/reverse-proxy.go:36 +0x170

2022-08-23T04:27:15.174 app[048da343] cdg [info] github.com/bots-garden/capsule/capsule-reverse-proxy/reverse-proxy.proxyRevision(0xc000145300)

2022-08-23T04:27:15.174 app[048da343] cdg [info] /github/workspace/capsule-reverse-proxy/reverse-proxy/reverse-proxy.go:82 +0x126
```

**Comment by k33g** [comment]
**TODO**:

- [ ]  don't start the capsule launcher instance if the wasm file does not exist
- [ ]  don't update the capsule reverse-proxy routes map
- [ ]  check if there is an impact on the worker (don't update the capsule worker routes map)
